### ISSUE TITLE
Использование наиболее базового интерфейса

### ISSUE THREAD

**Issue by truenorthpaul** [AlexKozachenko/LifeGame#11]
При выборе типа константы, поля, параметра, возвращаемого значения или переменной необходимо отдавать предпочтение наиболее базовому интерфейсу, который обладает требуемой функциональностью. Другими словами, не стоит использовать в качестве типа параметра метода тип `List<string>` если метод использует данный параметр только для обхода коллекции элементов. В такой ситуации достаточно было бы использовать тип `IEnumerable<string>`.

Поля, для которых данное правило не соблюдается:
- `LifeGame.KeyRead.keys`.

**Comment by truenorthpaul** [comment]
Поля, для которых данное правило не соблюдается:
- `LifeGame.Keyboard.keys`.

**Comment by truenorthpaul** [comment]
Вариант с коллекцией вполне подходил, как и массив, который стал ее заменой. Проблема была в типе самого поля. Сейчас вариант хуже прошлого, потому что явно указываются размер массива и индексы каждого элемента.

**Comment by truenorthpaul** [comment]
Стоит использовать коллекции-обобщения в качестве объектов и минимально возможный базовый интерфейс для поля.

**Comment by truenorthpaul** [comment]
Выбор `IEnumerable` был хорошим, но внутри класса требуется более конкретный интерфейс (,например `ICollection`), так как требуется добавление элементов. Наружу класс при этом должен выдавать именно `IEnumerable`. Не стоит брать более базовый интерфейс, если потом потребуется явно преобразовываться.

**Comment by AlexKozachenko** [comment]
Наследовать Keyboard от IEnumerable, а поле создавать по ссылке на ICollection?
Keyboard  : IEnumerable
...
ICollection<Key> keyList = new List<Key>();??

**Comment by truenorthpaul** [comment]
Наследовать интерфейс совсем не обязательно. Смысл в том, что если используется объект-коллекция (для поля, параметра или локальной переменной), стоит брать его тип как можно абстрактнее.
